[tool.yapf]
based_on_style = "google"
indent_width = 2
spaces_before_comment = 2
dedent_closing_brackets = true
column_limit = 80
continuation_indent_width = 2
split_all_top_level_comma_separated_values = true


[tool.pylint.messages_control]
disable = [
  "C0103",  # Invalid name
  "C0301",  # Too many lines in module
  "C0302",  # Too many lines in class
  "W0702",  # No exception
  "W1401",  # Too many statements
  "E0602",  # Undefined name
  "E0601",  # Undefined name
  "R0903",  # Too few public methods
  "R0913",  # Too many arguments
  "R0914",  # Too many local variables
  "W0311",  # Bad indentation
]

[tool.pylint.format]
max-line-length = 80


[tool.flake8]
max-line-length = 80
indent-size = 2
extend-ignore = [
  "F722",
  "W293",
  "W291",
  "E731",
  "E124",
  "W605",
  "E722",
  "F821",
  "E111",
  "E114",
]
